# Generated by Django 5.0.6 on 2024-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
