# Generated by Django 5.0.6 on 2024-07-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_newpost_author_alter_newpost_post_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Post',
        ),
    ]
