# Generated by Django 5.0.6 on 2024-07-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
